# Generated by Django 4.0.5 on 2022-08-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('repeatpassword', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('sname', models.CharField(max_length=300, null=True)),
                ('signup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.signup')),
            ],
        ),
    ]
