# Generated by Django 4.0.5 on 2022-08-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_Signup',
            new_name='AdminSignup',
        ),
    ]
