# Generated by Django 4.0.5 on 2022-08-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_admin_signup_adminsignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsignup',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='adminsignup',
            old_name='uname',
            new_name='username',
        ),
    ]
