# Generated by Django 4.0.5 on 2022-08-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_specific_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specific',
            old_name='signup',
            new_name='username',
        ),
    ]
