# Generated by Django 4.0.5 on 2022-08-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_pwd_adminsignup_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsignup',
            old_name='password',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='adminsignup',
            old_name='username',
            new_name='uname',
        ),
    ]
