# Generated by Django 4.0.5 on 2022-08-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_specific_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specific',
            name='username',
        ),
        migrations.AddField(
            model_name='specific',
            name='username',
            field=models.ManyToManyField(null=True, to='myapp.signup'),
        ),
    ]
