# Generated by Django 4.0.5 on 2022-08-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_specific_username_specific_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specific',
            name='username',
        ),
        migrations.AddField(
            model_name='specific',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.signup'),
        ),
    ]
